name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate Snake Animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Knitesh026
          outputs: dist/snake.svg

      # Step 3: Push the result back to the repository
      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generate snake animation"
          add: "dist/snake.svg"
